@startuml
'https://plantuml.com/sequence-diagram

class App{
- App : ArrayList<THE_LIST_OF_THE_PRODUCTS_HERE>
- SEARCHINGNOW
- mbusa : chking_to_see_if_availbl
}
class searchmerch{
- List<string> -> ArrayList
-the_final_answer -> SEARCHINGNOW
}
@enduml